/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 car.gltf 
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/2015-ford-mustang-rtr-6ceaeec6654848a48fdabc44de53fddc
Title: 2015 Ford Mustang RTR
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Car(props) {
  const { nodes, materials } = useGLTF('/car.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]}>
          <mesh geometry={nodes.FordChassis7_Mesh_M_Opaque_PlasticSmoothBlack_Max_FordM_Opaque_PlasticSmoothBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticSmoothBlack_Max1} />
          <mesh geometry={nodes.FordChassis7_Mesh_M_Opaque_PlasticSmoothBlack_Max_FordM_LightGlass_Red_Low_006_0.geometry} material={materials.FordM_LightGlass_Red_Low_006} />
          <mesh geometry={nodes.FordChassis7_Mesh_M_Opaque_PlasticSmoothBlack_Max_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} />
          <mesh geometry={nodes.FordChassis7_Mesh_M_Opaque_PlasticSmoothBlack_Max_FordM_Light_Max1_0.geometry} material={materials.FordM_Light_Max1} />
          <mesh geometry={nodes.FordChassis7_Mesh_M_Opaque_PlasticSmoothBlack_Max_FordM_CarPaint_Max_016_0.geometry} material={materials.FordM_CarPaint_Max_016} />
          <mesh geometry={nodes.FordChassis7_Mesh_M_Opaque_PlasticSmoothBlack_Max_FordM_Chassis_Max1_0.geometry} material={materials.FordM_Chassis_Max1} />
          <mesh geometry={nodes.FordChassis7_Mesh_M_Opaque_PlasticSmoothBlack_Max_FordM_Interior_Max1_0.geometry} material={materials.FordM_Interior_Max1} />
          <mesh geometry={nodes.FordChassis7_Mesh_M_Opaque_PlasticSmoothBlack_Max_FordM_CarPaintNormal_Max1_0.geometry} material={materials.FordM_CarPaintNormal_Max1} />
          <mesh geometry={nodes.FordChassis7_Mesh_M_Opaque_PlasticSmoothBlack_Max_FordM_Engine_Max1_0.geometry} material={materials.FordM_Engine_Max1} />
        </group>
        <group position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]}>
          <mesh geometry={nodes.RTR_BBumperChassisF6_Mesh_M_Chassis_Max_FordM_Chassis_Max1_0.geometry} material={materials.FordM_Chassis_Max1} />
          <mesh geometry={nodes.RTR_BBumperChassisF6_Mesh_M_Chassis_Max_FordM_Opaque_PlasticSmoothBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticSmoothBlack_Max1} />
        </group>
        <mesh geometry={nodes.FordDoorL_Glass4_Mesh_002_M_Opaque_PlasticRoughBlack_Max_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordDoorL_Glass4_Mesh_002_M_Opaque_PlasticRoughBlack_Max1_FordM_Glass_WindowFront_Low1_0.geometry} material={materials.FordM_Glass_WindowFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordDoorL4_Mesh_001_M_Interior_Max_FordM_Interior_Max1_0.geometry} material={materials.FordM_Interior_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordDoorL4_Mesh_001_M_Interior_Max1_FordM_Opaque_PlasticSmoothBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordDoorL4_Mesh_001_M_Interior_Max2_FordM_CarPaint_Max_016_0.geometry} material={materials.FordM_CarPaint_Max_016} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordDoorR_Glass4_Mesh_004_M_Opaque_PlasticRoughBlack_Max_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordDoorR_Glass4_Mesh_004_M_Opaque_PlasticRoughBlack_Max1_FordM_Glass_WindowFront_Low1_0.geometry} material={materials.FordM_Glass_WindowFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordDoorR4_Mesh_003_M_Interior_Max_FordM_Interior_Max1_0.geometry} material={materials.FordM_Interior_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordDoorR4_Mesh_003_M_Interior_Max1_FordM_Opaque_PlasticSmoothBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordDoorR4_Mesh_003_M_Interior_Max2_FordM_CarPaint_Max_016_0.geometry} material={materials.FordM_CarPaint_Max_016} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordGlass6_Mesh_005_M_Opaque_PlasticRoughBlack_Max_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordGlass6_Mesh_005_M_Opaque_PlasticRoughBlack_Max1_FordM_Glass_WindowSurroundFront_Low1_0.geometry} material={materials.FordM_Glass_WindowSurroundFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordGlass6_Mesh_005_M_Opaque_PlasticRoughBlack_Max2_FordM_Glass_WindowFront_Low1_0.geometry} material={materials.FordM_Glass_WindowFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordGlass6_Mesh_005_M_Opaque_PlasticRoughBlack_Max3_FordM_Glass_WindowSurroundFront_Low1_0.geometry} material={materials.FordM_Glass_WindowSurroundFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordGlass6_Mesh_005_M_Opaque_PlasticRoughBlack_Max4_FordM_Glass_WindowFront_Low1_0.geometry} material={materials.FordM_Glass_WindowFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordGlass6_Mesh_005_M_Opaque_PlasticRoughBlack_Max5_FordM_Glass_WindowSurroundFront_Low1_0.geometry} material={materials.FordM_Glass_WindowSurroundFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordGlass6_Mesh_005_M_Opaque_PlasticRoughBlack_Max6_FordM_Glass_WindowFront_Low1_0.geometry} material={materials.FordM_Glass_WindowFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordGlass6_Mesh_005_M_Opaque_PlasticRoughBlack_Max7_FordM_Glass_WindowSurroundFront_Low1_0.geometry} material={materials.FordM_Glass_WindowSurroundFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordGlass6_Mesh_005_M_Opaque_PlasticRoughBlack_Max8_FordM_Glass_WindowFront_Low1_0.geometry} material={materials.FordM_Glass_WindowFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordSteeringWheel5_Mesh_007_M_Interior_Max_FordM_Interior_Max1_0.geometry} material={materials.FordM_Interior_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordInterior5_Mesh_006_M_Interior_Max_FordM_Interior_Max1_0.geometry} material={materials.FordM_Interior_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordInterior5_Mesh_006_M_Interior_Max1_FordM_GlassOpaque_Mirror_Max_002_0.geometry} material={materials.FordM_GlassOpaque_Mirror_Max_002} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordBoot6_Mesh_008_M_Opaque_PlasticRoughBlack_Max_001_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordBoot6_Mesh_008_M_Opaque_PlasticRoughBlack_Max_002_FordM_Opaque_PlasticSmoothBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordBoot6_Mesh_008_M_Opaque_PlasticRoughBlack_Max_003_FordM_Badge_Max_006_0.geometry} material={materials.FordM_Badge_Max_006} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordBoot6_Mesh_008_M_Opaque_PlasticRoughBlack_Max_004_FordM_CarPaint_Max_016_0.geometry} material={materials.FordM_CarPaint_Max_016} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordBoot6_Mesh_008_M_Opaque_PlasticRoughBlack_Max_005_FordM_CarPaint_Trim_PianoBlack_Max1_0.geometry} material={materials.FordM_CarPaint_Trim_PianoBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordBumperChassisR5_Mesh_010_M_Chassis_Max_002_FordM_Chassis_Max1_0.geometry} material={materials.FordM_Chassis_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordBumperR6_Mesh_012_M_LicensePlate_Max_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordBumperR6_Mesh_012_M_LicensePlate_Max1_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordBumperR6_Mesh_012_M_LicensePlate_Max2_FordM_Glass_WindowFront_Low1_0.geometry} material={materials.FordM_Glass_WindowFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordBumperR6_Mesh_012_M_LicensePlate_Max3_FordM_Light_Max1_0.geometry} material={materials.FordM_Light_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordBumperR6_Mesh_012_M_LicensePlate_Max4_FordM_LightGlass_Red_Low_006_0.geometry} material={materials.FordM_LightGlass_Red_Low_006} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordBumperR6_Mesh_012_M_LicensePlate_Max5_FordM_CarPaint_Max_016_0.geometry} material={materials.FordM_CarPaint_Max_016} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordExhausts6_Mesh_014_M_Chassis_Max_003_FordM_Chassis_Max1_0.geometry} material={materials.FordM_Chassis_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordExhausts6_Mesh_014_M_Chassis_Max_004_FordM_Opaque_NickelRough_Max1_0.geometry} material={materials.FordM_Opaque_NickelRough_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordExhausts6_Mesh_014_M_Chassis_Max_005_FordM_Opaque_NickelSmooth_Max1_0.geometry} material={materials.FordM_Opaque_NickelSmooth_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordFenderFL6_Mesh_015_M_Badge_Max_001_FordM_Badge_Max_006_0.geometry} material={materials.FordM_Badge_Max_006} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordFenderFL6_Mesh_015_M_Badge_Max_002_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordFenderFL6_Mesh_015_M_Badge_Max_003_FordM_CarPaint_Max_016_0.geometry} material={materials.FordM_CarPaint_Max_016} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordFenderFL6_Mesh_015_M_Badge_Max_004_FordM_CarPaintNormal_Max1_0.geometry} material={materials.FordM_CarPaintNormal_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordFenderFR6_Mesh_016_M_Badge_Max_002_FordM_Badge_Max_006_0.geometry} material={materials.FordM_Badge_Max_006} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordFenderFR6_Mesh_016_M_Badge_Max_003_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordFenderFR6_Mesh_016_M_Badge_Max_004_FordM_CarPaint_Max_016_0.geometry} material={materials.FordM_CarPaint_Max_016} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordFenderFR6_Mesh_016_M_Badge_Max_005_FordM_CarPaintNormal_Max1_0.geometry} material={materials.FordM_CarPaintNormal_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordFendersChassisF6_Mesh_017_M_Chassis_Max_004_FordM_Chassis_Max1_0.geometry} material={materials.FordM_Chassis_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordFendersChassisR6_Mesh_018_M_Chassis_Max_005_FordM_Chassis_Max1_0.geometry} material={materials.FordM_Chassis_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordFendersR6_Mesh_019_M_CarPaint_Max_007_FordM_CarPaint_Max_016_0.geometry} material={materials.FordM_CarPaint_Max_016} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordHeadLightL6_Mesh_021_M_Light_Max_004_FordM_Light_Max1_0.geometry} material={materials.FordM_Light_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordHeadLightL6_Mesh_021_M_Light_Max_005_FordM_Glass_WindowFront_Low1_0.geometry} material={materials.FordM_Glass_WindowFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordHeadLightR6_Mesh_022_M_Light_Max_004_FordM_Light_Max1_0.geometry} material={materials.FordM_Light_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordHeadLightR6_Mesh_022_M_Light_Max_005_FordM_Glass_WindowFront_Low1_0.geometry} material={materials.FordM_Glass_WindowFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordHood6_Mesh_023_M_Opaque_PlasticRoughBlack_Max_007_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordHood6_Mesh_023_M_Opaque_PlasticRoughBlack_Max_008_FordM_GrilleA_Max_002_0.geometry} material={materials.FordM_GrilleA_Max_002} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordHood6_Mesh_023_M_Opaque_PlasticRoughBlack_Max_009_FordM_CarPaint_Max_016_0.geometry} material={materials.FordM_CarPaint_Max_016} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorBaseL6_Mesh_024_M_Opaque_PlasticSmoothBlack_Max_005_FordM_Opaque_PlasticSmoothBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorBaseL6_Mesh_024_M_Opaque_PlasticSmoothBlack_Max_006_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorBaseR6_Mesh_025_M_Opaque_PlasticSmoothBlack_Max_006_FordM_Opaque_PlasticSmoothBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorBaseR6_Mesh_025_M_Opaque_PlasticSmoothBlack_Max_007_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorL6_Mesh_026_M_Opaque_PlasticSmoothBlack_Max_007_FordM_Opaque_PlasticSmoothBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorL6_Mesh_026_M_Opaque_PlasticSmoothBlack_Max_008_FordM_Badge_Max_006_0.geometry} material={materials.FordM_Badge_Max_006} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorL6_Mesh_026_M_Opaque_PlasticSmoothBlack_Max_009_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorL6_Mesh_026_M_Opaque_PlasticSmoothBlack_Max_010_FordM_Glass_WindowFront_Low1_0.geometry} material={materials.FordM_Glass_WindowFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorL6_Mesh_026_M_Opaque_PlasticSmoothBlack_Max_011_FordM_Light_Max1_0.geometry} material={materials.FordM_Light_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorL6_Mesh_026_M_Opaque_PlasticSmoothBlack_Max_012_FordM_GlassOpaque_Mirror_Max_002_0.geometry} material={materials.FordM_GlassOpaque_Mirror_Max_002} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorL6_Mesh_026_M_Opaque_PlasticSmoothBlack_Max_013_FordM_CarPaint_Max_016_0.geometry} material={materials.FordM_CarPaint_Max_016} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorR6_Mesh_027_M_Opaque_PlasticSmoothBlack_Max_008_FordM_Opaque_PlasticSmoothBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorR6_Mesh_027_M_Opaque_PlasticSmoothBlack_Max_009_FordM_Badge_Max_006_0.geometry} material={materials.FordM_Badge_Max_006} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorR6_Mesh_027_M_Opaque_PlasticSmoothBlack_Max_010_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorR6_Mesh_027_M_Opaque_PlasticSmoothBlack_Max_011_FordM_Glass_WindowFront_Low1_0.geometry} material={materials.FordM_Glass_WindowFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorR6_Mesh_027_M_Opaque_PlasticSmoothBlack_Max_012_FordM_Light_Max1_0.geometry} material={materials.FordM_Light_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorR6_Mesh_027_M_Opaque_PlasticSmoothBlack_Max_013_FordM_GlassOpaque_Mirror_Max_002_0.geometry} material={materials.FordM_GlassOpaque_Mirror_Max_002} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordMirrorR6_Mesh_027_M_Opaque_PlasticSmoothBlack_Max_014_FordM_CarPaint_Max_016_0.geometry} material={materials.FordM_CarPaint_Max_016} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordTailLightL6_Mesh_031_M_LightGlass_Red_Low_003_FordM_LightGlass_Red_Low_006_0.geometry} material={materials.FordM_LightGlass_Red_Low_006} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordTailLightL6_Mesh_031_M_LightGlass_Red_Low_004_FordM_Light_Max1_0.geometry} material={materials.FordM_Light_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordTailLightR6_Mesh_032_M_LightGlass_Red_Low_003_FordM_LightGlass_Red_Low_006_0.geometry} material={materials.FordM_LightGlass_Red_Low_006} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.FordTailLightR6_Mesh_032_M_LightGlass_Red_Low_004_FordM_Light_Max1_0.geometry} material={materials.FordM_Light_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BBumperF6_Mesh_001_M_GrilleB_Max_RTR_BM_GrilleB_Max_002_0.geometry} material={materials.RTR_BM_GrilleB_Max_002} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BBumperF6_Mesh_001_M_GrilleB_Max1_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BBumperF6_Mesh_001_M_GrilleB_Max2_FordM_Opaque_PlasticSmoothBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BBumperF6_Mesh_001_M_GrilleB_Max3_FordM_Glass_WindowFront_Low1_0.geometry} material={materials.FordM_Glass_WindowFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BBumperF6_Mesh_001_M_GrilleB_Max4_FordM_Light_Max1_0.geometry} material={materials.FordM_Light_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BBumperF6_Mesh_001_M_GrilleB_Max5_FordM_CarPaint_Trim_PlasticSmoothBlack_Max1_0.geometry} material={materials.FordM_CarPaint_Trim_PlasticSmoothBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BBumperF6_Mesh_001_M_GrilleB_Max6_FordM_CarPaint_Max_016_0.geometry} material={materials.FordM_CarPaint_Max_016} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BDiffuser1_Mesh_002_M_Opaque_PlasticRoughBlack_Max_001_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BDiffuser1_Mesh_002_M_Opaque_PlasticRoughBlack_Max_002_FordM_Glass_WindowFront_Low1_0.geometry} material={materials.FordM_Glass_WindowFront_Low1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BDiffuser1_Mesh_002_M_Opaque_PlasticRoughBlack_Max_003_FordM_Opaque_PlasticSmoothBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BDiffuser1_Mesh_002_M_Opaque_PlasticRoughBlack_Max_004_FordM_Light_Max1_0.geometry} material={materials.FordM_Light_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BDiffuser1_Mesh_002_M_Opaque_PlasticRoughBlack_Max_005_RTR_BM_CarPaint_Trim_CarbonA_Max1_0.geometry} material={materials.RTR_BM_CarPaint_Trim_CarbonA_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BDiffuser1_Mesh_002_M_Opaque_PlasticRoughBlack_Max_006_FordM_LightGlass_Red_Low_006_0.geometry} material={materials.FordM_LightGlass_Red_Low_006} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BGrille6_Mesh_003_M_GrilleB_Max_001_RTR_BM_GrilleB_Max_002_0.geometry} material={materials.RTR_BM_GrilleB_Max_002} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BGrille6_Mesh_003_M_GrilleB_Max_002_FordM_Light_Max1_0.geometry} material={materials.FordM_Light_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BGrille6_Mesh_003_M_GrilleB_Max_003_FordM_Badge_Max_006_0.geometry} material={materials.FordM_Badge_Max_006} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BGrille6_Mesh_003_M_GrilleB_Max_004_RTR_BM_CarPaint_Trim_CarbonA_Max1_0.geometry} material={materials.RTR_BM_CarPaint_Trim_CarbonA_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BSkirts6_Mesh_004_M_Chassis_Max_001_FordM_Chassis_Max1_0.geometry} material={materials.FordM_Chassis_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BSkirts6_Mesh_004_M_Chassis_Max_002_FordM_Opaque_PlasticRoughBlack_Max1_0.geometry} material={materials.FordM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BSkirts6_Mesh_004_M_Chassis_Max_003_FordM_CarPaint_Max_016_0.geometry} material={materials.FordM_CarPaint_Max_016} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BSkirts6_Mesh_004_M_Chassis_Max_004_RTR_BM_CarPaint_Trim_CarbonA_Max1_0.geometry} material={materials.RTR_BM_CarPaint_Trim_CarbonA_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <mesh geometry={nodes.RTR_BSpoiler6_Mesh_005_M_CarPaint_Trim_CarbonA_Max_003_RTR_BM_CarPaint_Trim_CarbonA_Max1_0.geometry} material={materials.RTR_BM_CarPaint_Trim_CarbonA_Max1} position={[0, 0.155, 0.064]} rotation={[0.011, 0, 0]} />
        <group position={[0.801, 0.345, 1.429]} rotation={[0, 0, 0.017]}>
          <group position={[-0.033, 0, 0]}>
            <mesh geometry={nodes.polySurface209_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface208_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface207_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface206_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface205_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface204_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface203_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface202_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface201_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface200_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface199_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface198_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface197_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface196_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface195_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface194_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface193_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface192_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface191_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface190_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface189_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface188_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface187_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
          </group>
          <mesh geometry={nodes.polySurface183_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperBadgeA_f59116b1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperBadgeA_f59116b1} position={[-0.033, 0, 0]} />
          <group position={[-0.01, 0, 0]} scale={[1.024, 1.077, 1.077]}>
            <mesh geometry={nodes.rimMesh_Rim_B_0.geometry} material={materials.Rim_B} />
            <mesh geometry={nodes.rimMesh_rim_1_0.geometry} material={materials.rim_1} />
            <mesh geometry={nodes.rimMesh_rim_2_0.geometry} material={materials.rim_2} />
          </group>
          <mesh geometry={nodes.polySurface33_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface34_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface35_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface36_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface37_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface38_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface39_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface40_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface41_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface42_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface43_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface44_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface45_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface46_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface47_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface48_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface49_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface50_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface51_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface52_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface53_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface54_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface55_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface56_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface57_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface58_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface59_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface60_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface61_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface62_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface63_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface64_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface65_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface66_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface67_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface68_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface69_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface8_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface7_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface6_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface5_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface4_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface3_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface2_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface1_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
        </group>
        <group position={[-0.801, 0.345, 1.429]} rotation={[Math.PI, 0, -3.124]}>
          <group position={[-0.033, 0, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.polySurface232_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface231_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface230_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface229_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface228_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface227_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface226_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface225_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface224_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface223_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface222_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface221_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface220_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface219_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface218_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface217_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface216_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface215_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface214_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface213_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface212_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface211_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface210_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
          </group>
          <mesh geometry={nodes.polySurface184_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperBadgeA_f59116b1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperBadgeA_f59116b1} position={[-0.033, 0, 0]} />
          <group scale={[1.024, 1.077, 1.077]}>
            <mesh geometry={nodes.Mesh_Rim_B_0.geometry} material={materials.Rim_B} />
            <mesh geometry={nodes.Mesh_rim_1_0.geometry} material={materials.rim_1} />
            <mesh geometry={nodes.Mesh_rim_2_0.geometry} material={materials.rim_2} />
          </group>
          <mesh geometry={nodes.polySurface70_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface71_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface72_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface73_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface74_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface75_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface76_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface77_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface78_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface79_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface80_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface81_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface82_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface83_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface84_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface85_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface86_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface87_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface88_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface89_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface90_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface91_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface92_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface93_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface94_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface95_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface96_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface97_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface98_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface99_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface100_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface101_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface102_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface103_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface104_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface105_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface106_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface16_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface15_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface14_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface13_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface12_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface11_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface10_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface9_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
        </group>
        <group position={[0.812, 0.354, -1.289]} rotation={[0, 0, 0.017]}>
          <group position={[-0.033, 0, 0]}>
            <mesh geometry={nodes.polySurface233_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface234_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface235_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface236_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface237_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface238_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface239_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface240_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface241_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface242_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface243_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface244_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface245_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface246_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface247_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface248_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface249_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface250_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface251_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface252_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface253_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface254_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface255_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface256_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface257_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
          </group>
          <mesh geometry={nodes.polySurface185_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperBadgeA_f59116b1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperBadgeA_f59116b1} position={[-0.033, 0, 0]} />
          <group scale={[1.045, 1.077, 1.077]}>
            <mesh geometry={nodes.Mesh1_Rim_B_0.geometry} material={materials.Rim_B} />
            <mesh geometry={nodes.Mesh1_rim_1_0.geometry} material={materials.rim_1} />
            <mesh geometry={nodes.Mesh1_rim_2_0.geometry} material={materials.rim_2} />
          </group>
          <mesh geometry={nodes.polySurface24_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface23_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface22_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface21_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface20_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface19_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface18_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface17_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface107_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface108_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface109_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface110_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface111_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface112_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface113_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface114_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface115_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface116_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface117_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface118_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface119_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface120_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface121_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface122_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface123_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface124_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface125_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface126_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface127_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface128_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface129_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface130_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface131_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface132_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface133_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface134_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface135_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface136_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface137_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface138_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface139_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface140_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface141_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface142_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface143_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface144_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
        </group>
        <group position={[-0.812, 0.354, -1.289]} rotation={[Math.PI, 0, -3.124]}>
          <group position={[-0.033, 0, 0]} rotation={[-Math.PI, 0, Math.PI]} scale={[-1, 1, 1]}>
            <mesh geometry={nodes.polySurface282_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface281_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface280_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface279_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface278_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface277_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface276_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface275_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface274_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface273_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface272_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface271_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface270_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface269_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface268_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface267_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface266_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface265_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface264_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface263_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface262_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface261_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface260_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface259_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
            <mesh geometry={nodes.polySurface258_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperGloss_Material1} />
          </group>
          <mesh geometry={nodes.polySurface186_calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperBadgeA_f59116b1_0.geometry} material={materials.calipersFord_MustangGTFastbackTNR0_2018_CallipersCalliperBadgeA_f59116b1} position={[-0.033, 0, 0]} />
          <group scale={[1.045, 1.077, 1.077]}>
            <mesh geometry={nodes.Mesh2_Rim_B_0.geometry} material={materials.Rim_B} />
            <mesh geometry={nodes.Mesh2_rim_1_0.geometry} material={materials.rim_1} />
            <mesh geometry={nodes.Mesh2_rim_2_0.geometry} material={materials.rim_2} />
          </group>
          <mesh geometry={nodes.polySurface182_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface181_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface180_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface179_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface178_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface177_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface176_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface175_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface174_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface173_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface172_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface171_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface170_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface169_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface168_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface167_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface166_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface165_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface164_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface163_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface162_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface161_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface160_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface159_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface158_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface157_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface156_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface155_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface154_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface153_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface152_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface151_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface150_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface149_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface148_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface147_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface146_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface145_r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1_0.geometry} material={materials.r_TNRRims_93A20NaBrakeDisc_ForgedDrilled_Material1} position={[-0.033, 0, 0]} />
          <mesh geometry={nodes.polySurface32_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface31_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface30_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface29_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface28_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface27_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface26_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
          <mesh geometry={nodes.polySurface25_r_TNRRims_93A20NaTireBlur_Material1_0.geometry} material={materials.r_TNRRims_93A20NaTireBlur_Material1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/car.gltf')


export default Car;